spring:
  application:
    name: demo

server.port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health #,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces

  tracing:
    sampling:
      probability: 1.0